// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;

public class TestScenarioHardcoded {
    private WebDriver driver;
    private String idOffset;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();
        idOffset = String.valueOf((int) (Math.random() * 999));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test() {
        driver.get("https://opensource-demo.orangehrmlive.com/index.php/auth/login");
        driver.findElement(By.id("txtUsername")).click();
        driver.findElement(By.id("txtUsername")).sendKeys("Admin");
        driver.findElement(By.id("txtPassword")).click();
        driver.findElement(By.id("txtPassword")).sendKeys("admin123");
        driver.findElement(By.id("btnLogin")).click();
        driver.findElement(By.id("menu_admin_viewAdminModule")).click();
        WebElement element = driver.findElement(By.id("menu_admin_UserManagement"));
        new Actions(driver).moveToElement(element).perform();
        driver.findElement(By.id("menu_admin_viewSystemUsers")).click();
        driver.findElement(By.id("btnAdd")).click();
        driver.findElement(By.id("systemUser_employeeName_empName")).click();
        driver.findElement(By.id("systemUser_employeeName_empName")).sendKeys("John Smith");
        driver.findElement(By.id("systemUser_userName")).click();
        driver.findElement(By.id("systemUser_userName")).sendKeys("JohnSmith" + idOffset);
        driver.findElement(By.id("systemUser_password")).click();
        driver.findElement(By.id("systemUser_password")).sendKeys("admin123");
        driver.findElement(By.id("systemUser_confirmPassword")).click();
        driver.findElement(By.id("systemUser_confirmPassword")).sendKeys("admin123");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(1));
        driver.findElement(By.id("btnSave")).click();
        driver.findElement(By.id("searchSystemUser_userName")).click();
        driver.findElement(By.id("searchSystemUser_userName")).sendKeys("JohnSmith" + idOffset);
        driver.findElement(By.id("searchBtn")).click();
        driver.findElement(By.id("resetBtn")).click();
        driver.findElement(By.xpath("//tr[td[a[contains(text(),'JohnSmith" + idOffset + "')]]]//input")).click();
        driver.findElement(By.id("btnDelete")).click();
        driver.findElement(By.id("dialogDeleteBtn")).click();
    }
}
